name: Semgrep 
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Semgrep
        uses: njjetha/semgrep-action@master
        with:
          token: ${{ secrets.SEMGREP_APP_TOKEN }}