name: Checker 
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  checker:
    uses: njjetha/reusable-workflows/.github/workflows/build.yml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}